name: YsmDisplay
version: $version
main: org.windy.ysmDisplay.YsmDisplay
api-version: '1.21'
depend:
  - NBTAPI
softdepend:
  - PlaceholderAPI
commands:
  ydp:
    description: "Test command for YsmDisplay"
    usage: "/ydp test"
